const POSTS_SUCCESS = 'POSTS_SUCCESS';
const POSTS_ERROR = 'POSTS_ERROR';
const POSTS_REQUEST = 'POSTS_REQUEST';
const POSTS_REALTIME_RECEIVED = 'POSTS_REALTIME_RECEIVED';
const POSTS_REALTIME_PUSH = 'POSTS_REALTIME_PUSH';

export {
  POSTS_ERROR,
  POSTS_REQUEST,
  POSTS_SUCCESS,
  POSTS_REALTIME_RECEIVED,
  POSTS_REALTIME_PUSH,
};
