const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';
const COMMENTS_ERROR = 'COMMENTS_ERROR';
const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
const COMMENTS_REALTIME_RECEIVED = 'COMMENTS_REALTIME_RECEIVED';
const COMMENTS_REALTIME_PUSH = 'COMMENTS_REALTIME_PUSH';

export {
  COMMENTS_ERROR,
  COMMENTS_REQUEST,
  COMMENTS_SUCCESS,
  COMMENTS_REALTIME_RECEIVED,
  COMMENTS_REALTIME_PUSH,
};
