export const SET_USER_NAME = 'SET_USER_NAME';
export const USER_DATA_REQUESTED = 'USER_DATA_REQUESTED';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';
export const USER_DATA_SUCCEEDED = 'USER_DATA_SUCCEEDED';
